version: "3.9"
services:
  db:
    image: postgres:16
    container_name: monassurance-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-monassurance}
      POSTGRES_USER: ${POSTGRES_USER:-monassurance}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-devpass}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: .
    container_name: monassurance-backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER:-monassurance}:${POSTGRES_PASSWORD:-devpass}@db:5432/${POSTGRES_DB:-monassurance}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-changeme}
      JWT_ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    ports:
      - "8000:8000"
    command: ["sh", "-c", "alembic upgrade head && uvicorn backend.app.main:app --host 0.0.0.0 --port 8000"]
volumes:
  postgres_data:
