###############
# Ruff config #
###############
###############
# Ruff config #
###############
# Configuration progressive pour B4 - CI strict (étape 1)

line-length = 110

[lint]
# Ensemble progressif: erreurs de base + imports + pyupgrade + sécurité critique
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes  
    "I",   # isort
    "UP",  # pyupgrade (modernisation Python)
    "B",   # flake8-bugbear (erreurs communes)
    "S110", # try-except-pass detection
    "S603", # subprocess without shell=True
    "S314", # xml parsing vulnerability
    "PLC0415", # import at top level
]

ignore = [
    "E203", "E266", "E501",  # style conflicts avec formatter
    "E402",  # module level import (à corriger progressivement)
    "B008",  # Do not perform function call in argument defaults (FastAPI pattern)
    "PLC0415", # import should be at top-level (imports locaux intentionnels)
    "S110",  # try-except-pass detected (fallbacks intentionnels)
]

[lint.per-file-ignores]
"tests/*" = ["S101","S105"]
"backend/app/db/models/__init__.py" = ["F401"]
"manage.py" = ["S603"]  # subprocess usage acceptable dans scripts CLI
"scripts/*" = ["S314", "S603"]  # scripts utilitaires - sécurité moins critique
"backend/app/api/routes/*" = ["B904"]  # FastAPI routes - raise intentionnels pour HTTP errors
"backend/app/services/*" = ["B904"]  # services - raise intentionnels pour business logic
# Scripts de gestion Celery - subprocess usage OK
"celery_manager.py" = ["S603"]
"celery_control.py" = ["S603"]
"start_redis_dev.py" = ["S603"]
"test_*.py" = ["S603"]  # Tests - subprocess pour simulation OK
"b4_*.py" = ["S603", "I001"]  # Scripts B4 temporaires

