###############
# Ruff config #
###############
# Objectif initial: lint de base (E,F,I) pour CI verte rapide. On élargira plus tard.

line-length = 110

[lint]
select = ["E","F","I"]
# E402: imports après docstring autorisés ici
# E203/E266/E501: style/longueur gérés ailleurs au besoin
ignore = ["E203","E266","E501","E402"]

[lint.per-file-ignores]
"tests/*" = ["S101","S105"]
"backend/app/db/models/__init__.py" = ["F401"]

