def sha256_hex(data: bytes) -> str: ...

def store_template_bytes(data: bytes, filename: str | None = ..., content_type: str | None = ...) -> str: ...

def read_template_text_from_file(path: str) -> str: ...
