name: Frontend E2E Type Check

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-e2e-typecheck.yml'
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-e2e-typecheck.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-typecheck:
    name: Type Check Frontend + E2E
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Type check (app)
        run: npm run type-check

      - name: Type check (e2e tests)
        run: npm run type-check:e2e

      - name: Summary
        run: |
          echo "### Frontend Type Check" >> $GITHUB_STEP_SUMMARY
          echo "App & E2E type-check passed." >> $GITHUB_STEP_SUMMARY
