name: frontend-openapi-types-check

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  gen-openapi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt

      - name: Install backend deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Start backend (OpenAPI provider)
        run: |
          python -m uvicorn backend.app.main:app --host 127.0.0.1 --port 8000 &
          echo $! > uvicorn.pid
      
      - name: Wait for API to be ready
        run: |
          for i in {1..30}; do
            if curl -sSf http://127.0.0.1:8000/api/v1/openapi.json > /dev/null; then
              echo "API is up"; break
            fi
            sleep 1
          done

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: |
            frontend/package-lock.json
            frontend/package.json

      - name: Install frontend deps
        working-directory: frontend
        run: |
          npm install

      - name: Generate OpenAPI types
        working-directory: frontend
        env:
          BACKEND_URL: http://127.0.0.1:8000
        run: npm run gen:api

      - name: Check that no diff is introduced
        run: |
          git diff --exit-code -- frontend/src/lib/api.types.ts || {
            echo "\nOpenAPI types out of date. Run 'npm run gen:api' in frontend and commit the changes."; exit 1; }

      - name: Stop backend
        if: always()
        run: |
          if [ -f uvicorn.pid ]; then kill $(cat uvicorn.pid) || true; fi

  frontend-lint-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: |
            frontend/package-lock.json
            frontend/package.json

      - name: Install frontend deps
        working-directory: frontend
        run: |
          # Utiliser ci si lockfile présent; sinon install standard
          if [ -f package-lock.json ]; then npm ci; else npm install; fi

      - name: Lint
        working-directory: frontend
        run: npm run lint

      - name: Type check
        working-directory: frontend
        run: |
          if [ -f tsconfig.json ]; then \
            if npm run | grep -q " type-check"; then npm run type-check; else npx --yes typescript --noEmit; fi; \
          else \
            echo "No tsconfig.json found, skipping type-check"; \
          fi

      - name: Build
        working-directory: frontend
        env:
          NEXT_PUBLIC_API_BASE: http://127.0.0.1:8000
          NEXT_TELEMETRY_DISABLED: '1'
        run: npm run build
